### ISSUE TITLE
intsaller

### ISSUE THREAD

**Issue by yinlinghunjiang** [UvUno/pockethold#60]
When i use pockethold to install 3rd party Flarum on my vps(i don't have ssh permission),i got HTTP 500 ERROR
How can i solve it？
![1](https://user-images.githubusercontent.com/68178871/125275365-804f6b80-e341-11eb-8d85-9ff5d94a61f0.png)
![2](https://user-images.githubusercontent.com/68178871/125275370-82192f00-e341-11eb-9588-eee3af986db1.png)
Thanks！

**Comment by lem0nb** [comment]
php7.3 it is ok
